from pylab import *
import scipy.signal as sp
import numpy as np
p1 = np.poly1d([1,.5])
p2 = np.poly1d([1,0,2.25])
p3 = np.poly1d([1,1,2.5])
X1 = sp.lti(p1,p2*p3)
t,x = sp.impulse(X1,None,linspace(0,50,501))
plot(t,x)
xlabel("Time")
ylabel("X(t)")
title("X(t) with delay .5")
show()
#---------------part2 
p1 = np.poly1d([1,.05])
p2 = np.poly1d([1,0,2.25])
p3 = np.poly1d([1,.1,2.2525])
X1 = sp.lti(p1,p2*p3)
t,x = sp.impulse(X1,None,linspace(0,50,501))
plot(t,x)
xlabel("Time")
ylabel("X(t)")
title("X(t) with much smaller delay as .05")
show()
#----------------part3
for i in arange(1.4,1.65,.05):
    p1 = np.poly1d([1,.05])
    p2 = np.poly1d([1,0,2.25])
    p3 = np.poly1d([1,.1,i**2+.0025])
    F = sp.lti(p1,p3)
    H = sp.lti(1,p2)
    t,Ft = sp.impulse(F,None,linspace(0,50,501))
    t,y,svsec = sp.lsim(H,Ft,t)
    plot(t,y)
xlabel("Time")
ylabel("X")
title("plot of X with various frequencies")
legend(("w = 1.4","w = 1.45","w = 1.5","w = 1.55","w = 1.6"))
show()
#---------------part 4 
p4 = np.poly1d([1,0,2])
p5 = np.poly1d([1,0,3,0])
X = sp.lti(p4,p5)
t,x = sp.impulse(X,None,linspace(0,50,501)) 
plot(t,x,'b-')
#show() 
Y = sp.lti(2,p5)
t,y = sp.impulse(Y,None,linspace(0,50,501))
plot(t,y,'r-')
legend(("X","Y"))
xlabel("Time")
ylabel("Y")
title("plot for question 4")
show()
#------------------part5
p6 = np.poly1d([10**-12,10**-4,1])
H_lc = sp.lti(1,p6)
w,S,phi = H_lc.bode()
subplot(2,1,1)
semilogx(w,S)
xlabel("frequency on log scale")
ylabel("Magnitude")
title ("Bode plot of the given filter")
subplot(2,1,2)
semilogx(w,phi)
xlabel("Frequency")
ylabel("Phase")
title("")
show()
#-----------------part 6
t  = arange(0,10**-2,10**-7)
V_i = cos((10**3)*t) - cos((10**6)*t)
t,V,svsec = sp.lsim(H_lc,V_i,t)
plot(t,V)
xlabel("Time")
ylabel("Output")
title("plot of the output of the given filter")
show()